DROP TABLE DA.STATISTIKAUPISANIHKURSEVA;

CREATE TABLE DA.STATISTIKAUPISANIHKURSEVA (
    IDPREDMETA INTEGER NOT NULL,
    SKGODINA SMALLINT NOT NULL,
    BROJSTUDENATA INTEGER,
    BROJPOLAGANJA INTEGER,
    PONISTENI SMALLINT NOT NULL,
    PRIMARY KEY (IDPREDMETA, SKGODINA),
    CONSTRAINT FK_PREDMET FOREIGN KEY (IDPREDMETA)
        REFERENCES DA.PREDMET (ID)
        ON DELETE CASCADE
);