DROP TABLE STATISTIKA_UPISANIH_KURSEVA;

CREATE TABLE STATISTIKA_UPISANIH_KURSEVA (
    ID_PREDMETA INTEGER NOT NULL,
	GODINA SMALLINT NOT NULL,
	BROJ_STUDENATA INTEGER,
	BROJ_POLAGANJA INTEGER,
	PONISTENI SMALLINT NOT NULL,
	PRIMARY KEY (ID_PREDMETA, GODINA),
	CONSTRAINT FK_PREDMET FOREIGN KEY (ID_PREDMETA)
		REFERENCES PREDMET (ID_PREDMETA)
		ON DELETE CASCADE
);