CREATE TABLE UKUPNI_BODOVI (
    INDEKS  INTEGER     NOT NULL,
    IME     VARCHAR(25) NOT NULL,
    PREZIME VARCHAR(25) NOT NULL,
    BODOVI  INTEGER     NOT NULL,
    PRIMARY KEY(INDEKS),
    FOREIGN KEY(INDEKS) REFERENCES DOSIJE    
);

INSERT      INTO UKUPNI_BODOVI
SELECT      D.INDEKS, 
            IME, 
            PREZIME, 
            SUM(CASE 
                WHEN OCENA > 5 AND STATUS_PRIJAVE = 'o' THEN P.BODOVI 
                ELSE 0 
                END) UKUPNO_BODOVA
FROM        DOSIJE D JOIN
            ISPIT I ON D.INDEKS = I.INDEKS JOIN
            PREDMET P ON I.ID_PREDMETA = P.ID_PREDMETA
GROUP BY    D.INDEKS, IME, PREZIME
ORDER BY    UKUPNO_BODOVA DESC;
